### ISSUE TITLE
Not all roads traced

### ISSUE THREAD

**Issue by philam** [jgc234/optiburb#5]
Thanks for this code, it's very interesting!

Just playing around with it and for some reason it misses a couple of random streets and roads within the suburb. There aren't any restrictions or other tags that prevent them from being included.

Example below for Fairfield as a test (loaded into RideWithGPS):

![](https://user-images.githubusercontent.com/6771240/89007158-8ecc8f00-d34b-11ea-979f-f84224995ab8.JPG)

**Comment by jgc234** [comment]
I wouldn't ride on Station Street either..   What arguments did you supply?

**Comment by jgc234** [comment]
Looks OK on mine (current master).. I did fix up an option that wasn't running the simplify_gpx by default.  Also, are you doing an autotrace in RWGPS, or is that the raw import?

```bash
./optiburb.py --debug=debug "fairfield, city of yarra, victoria, australia"
```

![Screen Shot 2020-07-31 at 16 51 50](https://user-images.githubusercontent.com/21459116/89008817-ad805500-d34e-11ea-94ae-3a66db4cb91c.png)

**Comment by jgc234** [comment]
Oh, I've managed to reproduce your picture by running an auto-route in RWGPS. That's a nice way to get turn-by-turn, but it seems to takes some shortcuts..  I'm keen to write my own turn-by-turn one day, but I'm not there yet.

![Screen Shot 2020-07-31 at 16 59 06](https://user-images.githubusercontent.com/21459116/89009073-33040500-d34f-11ea-83a5-603d5cf694e0.png)

**Comment by philam** [comment]
Oh right thank you! I guess I'll just deal with the raw import for now :)
