### ISSUE TITLE
Multithread possible?

### ISSUE THREAD

**Issue by ghost** [jgc234/optiburb#9]
Hi!
Thanks a lot for sharing the script with us.
Q: Ist it somehow possible to utilize all cores available on a machine for speeding up the calculation?
Currently I have 2 jobs running and only 2 cores are in use.
System: virtual debian 10.5 instance w/ currently 4 cores (12 possible) and 16GB RAM (256GB possible)
![image](https://user-images.githubusercontent.com/47909780/89523453-29611e00-d7e3-11ea-94e4-65d153ed68ff.png)

**Comment by jgc234** [comment]
Yeah, it's sad to watch isn't it.  The algorithm that's sucking most of the CPU is well suited to parallelisation.. But Python isn't.. Python supports threads, but it only runs one at a time.  I could split it into multiple processes (again, one thread each), and pass out a block of processing for each one, and gather the results..  I'm in the process of re-writing all this in another language.

**Comment by ghost** [comment]
Cool!
Many thanks Jim!
